name: CouncilBot Post

on:
  schedule:
    - cron: '5 * * * *'  # every hour at :05
  workflow_dispatch: {}

permissions:
  contents: write  # allow committing posted state back to repo

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: Fetch latest documents
        run: |
          python m9_unified_scraper.py

      - name: Post one document (no summary)
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          MAX_POSTS_PER_RUN: '1'
          PER_COUNCIL_COOLDOWN_HOURS: '6'
          POST_SUMMARY: '0'
          FAST_PREVIEW: '1'
        run: |
          python scripts/run_scheduler.py --live

      - name: Commit posted state
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          # Force-add JSON outputs even if gitignored
          git add -f posted_bluesky.json m9_scraper_results.json || true
          git commit -m "Update posted state [skip ci]" || echo "No changes"
          git push

      - name: Upload results artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scrape-results-${{ github.run_number }}
          path: |
            m9_scraper_results.json
            posted_bluesky.json
          if-no-files-found: ignore
          retention-days: 14
