name: Post to BlueSky

on:
  schedule:
    - cron: '35 * * * *'  # Run at :35 every hour
  workflow_dispatch:
    inputs:
      max_posts:
        description: 'Maximum number of posts'
        required: false
        default: '3'

jobs:
  post:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 python-dateutil
        pip install "atproto>=0.0.49,<1.0"
        pip install python-dotenv pandas
    
    - name: Post to BlueSky
      env:
        BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
        BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
      run: |
        MAX_POSTS="${{ github.event.inputs.max_posts }}"
        if [ "$MAX_POSTS" == "" ]; then
          MAX_POSTS="3"
        fi
        python scripts/run_scheduler.py --live --max-posts $MAX_POSTS
    
    - name: Commit posting record
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add posted_bluesky.json posts.md || true
        git diff --staged --quiet || git commit -m "Update posting records [skip ci]"
        git push || true
